Fréquence des troubles occulumoteurs

In [1]:
import pandas as pd
df=pd.read_csv('C:\\Users\\jorda\\PycharmProjects\\Aicha_These\\data\\Thesis_Aicha_Data V3.csv', sep=";")
df

,Sexe,Mode_entree_note,Mode_entree,Age_debut_symptomes,Symptomes_prodromaux,TCSP_prodr,Syndrome_extrapyramidal,Delai_syndrome_extrapyramidal,Symptomes_cognitifs,Date_symptomes_cognitifs,Symptomes_psychiatriques,Delai_symptomes_psychiatriques,Trouble_oculomoteur,Symptomes_moteurs,Idees_delirantes,Delai_fluctuations,Nom Mode_entree,Tranche_age
0,Feminin,"Troubles mnésiques, désorientation",Trouble Cognitfs,78.0,Non,Non,Oui,"0,5",1.0,0,Oui,"0,5",Non,Oui,Non,0.0,Trouble Cognitfs,77-100
1,Masculin,Cognitif (2010) : troubles mnésiques,Trouble Cognitfs,63.0,Oui,Oui,Non,NaN,1.0,0,Oui,6,NSP,Non,NaN,7.0,Trouble Cognitfs,0-65
2,Masculin,Cognitif (2013) : troubles dyséxécutifs,Trouble Cognitfs,58.0,NaN,Oui,Oui,4,1.0,0,Oui,3,NSP,NaN,NaN,3.0,Trouble Cognitfs,0-65
3,Masculin,Cognitif (2012) : troubles du langage et de la...,Trouble Cognitfs,52.0,Oui,Oui,Oui,0,1.0,0,Oui,2,NSP,Oui,NaN,1.0,Trouble Cognitfs,0-65
4,Feminin,Psychiatrique (2016) : troubles du comportemen...,Trouble Psychatrique,71.0,NaN,NaN,Non,NaN,1.0,1,Oui,0,NSP,Non,Oui,NaN,Trouble Psychatrique,66-75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,Masculin,Plainte cognitive,Trouble Cognitfs,76.0,NaN,NaN,Oui,NaN,1.0,0,Oui,NaN,NaN,Oui,Oui,NaN,Trouble Cognitfs,77-100
106,Masculin,Plainte cognitive,Trouble Cognitfs,48.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Trouble Cognitfs,0-65
107,Masculin,Plainte cognitive,Trouble Cognitfs,52.0,NaN,NaN,Oui,3,1.0,0,Oui,NaN,NaN,Oui,Oui,3.0,Trouble Cognitfs,0-65
108,Masculin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Masculin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
df2=df[['Trouble_oculomoteur','Tranche_age']]

In [3]:
occulus=df2[df2['Trouble_oculomoteur']=='Oui' ]
occulus

   Trouble_oculomoteur Tranche_age
39                 Oui       66-75
58                 Oui      77-100
75                 Oui        0-65
76                 Oui      77-100
87                 Oui        0-65
88                 Oui        0-65

In [4]:
import plotly.express as px

counts = occulus[['Trouble_oculomoteur','Tranche_age']].value_counts().reset_index(name='counts')
counts

  Trouble_oculomoteur Tranche_age  counts
0                 Oui        0-65       3
1                 Oui      77-100       2
2                 Oui       66-75       1

In [5]:
fig = px.bar(
    counts,
    x='Tranche_age',
    y='counts',
    text='counts',
    title='Fréquence des troubles oculomoteurs'
)

fig.show()